apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
      annotations:
        eks.amazonaws.com/fargate-profile: my-eks-farget
    spec:
      containers:
        - name: my-app-container
          image: 780799328195.dkr.ecr.us-east-1.amazonaws.com/eca-repo:7
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
